# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feeders.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feeders.proto',
  package='',
  serialized_pb=_b('\n\rfeeders.proto\"*\n\x06\x46\x65\x65\x64\x65r\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\"#\n\x07\x46\x65\x65\x64\x65rs\x12\x18\n\x07\x66\x65\x65\x64\x65rs\x18\x01 \x03(\x0b\x32\x07.FeederB/\n-edu.usf.ratsim.robot.ssl.sensefeeder.protobuf')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEEDER = _descriptor.Descriptor(
  name='Feeder',
  full_name='Feeder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Feeder.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='Feeder.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Feeder.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=59,
)


_FEEDERS = _descriptor.Descriptor(
  name='Feeders',
  full_name='Feeders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feeders', full_name='Feeders.feeders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=96,
)

_FEEDERS.fields_by_name['feeders'].message_type = _FEEDER
DESCRIPTOR.message_types_by_name['Feeder'] = _FEEDER
DESCRIPTOR.message_types_by_name['Feeders'] = _FEEDERS

Feeder = _reflection.GeneratedProtocolMessageType('Feeder', (_message.Message,), dict(
  DESCRIPTOR = _FEEDER,
  __module__ = 'feeders_pb2'
  # @@protoc_insertion_point(class_scope:Feeder)
  ))
_sym_db.RegisterMessage(Feeder)

Feeders = _reflection.GeneratedProtocolMessageType('Feeders', (_message.Message,), dict(
  DESCRIPTOR = _FEEDERS,
  __module__ = 'feeders_pb2'
  # @@protoc_insertion_point(class_scope:Feeders)
  ))
_sym_db.RegisterMessage(Feeders)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n-edu.usf.ratsim.robot.ssl.sensefeeder.protobuf'))
# @@protoc_insertion_point(module_scope)
